"""Offline regression for positive-price search preselection; no DB connection."""
import ast
import sqlite3
from pathlib import Path

root = Path(__file__).resolve().parents[1]
tree = ast.parse((root / "app/search/search.py").read_text(encoding="utf-8"))
node = next(n for n in tree.body if isinstance(n, ast.Assign)
            and any(isinstance(t, ast.Name) and t.id == "_ORDER_BY" for t in n.targets))
# 只读常量项。WAVE08 合入后 "roi" 一项是 roi_order_sql() 生成的表达式(不是字面量),
# 它的正确性由 tests/test_roi_*_offline.py 专门覆盖;这里确认它存在即可。
order = {ast.literal_eval(k): ast.literal_eval(v) for k, v in zip(node.value.keys, node.value.values)
         if not isinstance(v, ast.expr) or not any(isinstance(x, ast.Call) for x in ast.walk(v))}
roi_keys = [ast.literal_eval(k) for k, v in zip(node.value.keys, node.value.values)
            if any(isinstance(x, ast.Call) for x in ast.walk(v))]
assert roi_keys == ["roi"], f"only the ROI entry may be generated by code, got {roi_keys}"
assert order["price_desc"] == "price DESC, "
assert "CASE WHEN price > 0 THEN 0 ELSE 1 END" in order["price_asc"]

db = sqlite3.connect(":memory:")
db.execute("CREATE TABLE properties (id INTEGER, price INTEGER)")
db.executemany("INSERT INTO properties VALUES (?, ?)",
               [(1, 0), (2, -1), (3, 500000), (4, 300000)])
def sorted_ids(limit):
    return [row[0] for row in db.execute(
        "SELECT id FROM properties ORDER BY " + order["price_asc"]
        + "id LIMIT ?", (limit,))]
assert sorted_ids(4) == [4, 3, 2, 1]
assert sorted_ids(2) == [4, 3], "invalid prices must not consume the valid candidate pool"
print("PASS: positive-price SQL preselection; zero and negative prices last")
